import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// ✅ Correct
import "@livekit/components-styles";
import { ClerkProvider } from "@clerk/nextjs"; 
import Navbar from "@/components/navbar"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Course Generator",
  description: "Generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* 1. Navbar stays fixed at the top */}
          <Navbar />
          
          {/* 2. PUSH CONTENT DOWN so it doesn't hide behind the navbar */}
          {/* We use 'pt-24' (padding-top: 6rem) to create safe space */}
          <div className="pt-24 min-h-screen"> 
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}